### PR TITLE
MobileUI job start: complete the browserless recovery harness fake page

### PR DESCRIPTION
**Pull request by teosarca**
Two commits, both confined to naming and to a test double. No functional change anywhere.

## 1. Complete the browserless recovery harness fake page (test-only)

`e2e/mobile-webui/tests/harness/jobStartRecovery.test.js` installs a scripted fake page via `setCurrentPage(fakePage)` in `beforeEach`. The fake implements only `locator()`. This commit gives it inert `on()` / `off()` as well.

### Why — a semantic merge conflict, fixed at the origin

`setCurrentPage` (in `e2e/mobile-webui/tests/utils/common.js`) diverged between branches:

- on this branch it is a bare assignment, so a fake implementing only `locator()` is sufficient;
- on `new_dawn_uat` the same function was independently extended to attach a console recorder, which calls `currentPage.on('console', handler)` and `currentPage.off(handler)`.

So the incomplete fake is only latently broken here. When the harness file reached `new_dawn_uat` the merge was **textually clean** but semantically broken: `beforeEach` called `setCurrentPage(fakePage)`, the recorder tried to register a listener on a page that has none, and all four tests failed deterministically with `TypeError: currentPage.on is not a function` — before any test body ran.

Caught on the merge PR https://github.com/metasfresh/metasfresh/pull/25703 (`mobile test`: 372 passed, 4 failed).

This harness file exists **only** on this branch, which makes this branch the single origin of the trap. Completing the fake here closes it for every branch that later receives the file, instead of repairing it once per destination. The same hunk is already applied and verified on the merge branch, so the two will not conflict when they meet.

Inert is sufficient: nothing in this file asserts on console output, and inert `on`/`off` satisfy both variants of `setCurrentPage`.

## 2. Boolean predicate prefixes (raised in review)

`docs/coding-rules/javascript-general.md` § 1 requires every boolean in JS/JSX/TS — including a plain `const`/`let` in mobile-webui or the `e2e/` suites — to carry an affirmative-predicate prefix (`is`/`has`/`can`/`should`/`was`/`did`/`will`). A bare participle reads as a noun at the call site: `if (arrived)` is ambiguous where `if (hasArrived)` is a question. Past participle takes `has`.

Nine references across three files, renamed at the branch the code was authored on so the names do not diverge from their source and conflict on every future merge train:

| File | Rename | Refs |
|---|---|---|
| `misc/services/mobile-webui/mobile-webui-frontend/src/api/launchers.js` | `subscriptionActive` → `isSubscriptionActive` | 3 |
| `e2e/mobile-webui/tests/utils/screens/picking/PickingJobsListScreen.js` | `arrived` → `hasArrived` (both sites) | 4 |
| `e2e/mobile-webui/tests/utils/screens/distribution/DistributionJobsListScreen.js` | `arrived` → `hasArrived` | 2 |

`launchers.js` is the only production file touched. `isSubscriptionActive` is a local `let` inside one `useEffect` closure with no exported surface, so behaviour is identical. In `PickingJobsListScreen.js` both call sites are renamed — the one in `startJobByDocumentNo` and the pre-existing one in `tapLauncherUntilJobScreen` — rather than leaving an inconsistent third behind. A grep for the old names over the three files returns nothing.

## Verification

Both run locally on this branch at the current HEAD.

**Browserless recovery harness** — `e2e/mobile-webui`, `playwright test tests/harness/jobStartRecovery.test.js --reporter=line`: **4 passed**. Also 4 passed on the unmodified branch tip before commit 1, since the added `on`/`off` are unused until the console recorder arrives — the value of commit 1 is on the destination branches, not here. The test is browserless (no app server, no database).

**mobile-webui frontend jest** — `CI=true react-scripts test --watchAll=false`, full suite unfiltered: **5 failed / 14 passed suites, 13 failed / 203 passed of 216 tests** — and **byte-for-byte identical before and after the renames** (same five suites, same counts), which is the evidence that the renames are behaviour-neutral. Those 13 failures are pre-existing on this branch and unrelated to this PR (QR-code parsing, the manufacturing-issue reducer, `PickLineScanScreen`, `bounceHome`). `launchersFrameAfterTeardownIgnored.test.js` — the suite that actually covers the renamed teardown guard in `launchers.js` — passes in both runs.

## No reformatting

The `e2e/mobile-webui` project ships no eslint or prettier config, and `jobStartRecovery.test.js` already fails default-prettier at HEAD, so everything outside the hunks above is left byte-identical deliberately — reformatting would only bloat the diff.

### CODE REVIEW

**Comment by teosarca** [comment]
## CI audit — every failing check on this PR

**Nothing on this PR is caused by its own changes.** This PR is 4 files: 6 added lines in a browserless harness test, inert `on`/`off` on its fake page, and an affirmative-predicate rename of two local booleans (`subscriptionActive` → `isSubscriptionActive`, `arrived` → `hasArrived`) — 9 insertions, 9 deletions, no behaviour change.

### Current head ([commit](https://github.com/metasfresh/metasfresh/commit/eb8ee8a01274627a8882d2abe32de5d0b308d7fb)) — [this CI run](https://github.com/metasfresh/metasfresh/actions/runs/33637570587)

| Check | Failing test | Classification | Evidence |
|---|---|---|---|
| [`frontend`](https://github.com/metasfresh/metasfresh/actions/runs/33637570587/job/100272616850) | none — died pushing the image | **Infrastructure** — internal flaky-case 90 (ghcr.io registry-egress outage) | `Put "https://ghcr.io/v2/metasfresh/metas-mobile-test/manifests/…": net/http: TLS handshake timeout`, both attempts |
| [`db-images`](https://github.com/metasfresh/metasfresh/actions/runs/33637570587/job/100278810489) | none | **Infrastructure** — flaky-case 90 | same `ghcr.io … TLS handshake timeout` |

Repo-wide, not this branch: [this run](https://github.com/metasfresh/metasfresh/actions/runs/33633426583) on `new_dawn_uat_MobileMfgEditableAttributes` has all five of its failing jobs on the identical `ghcr.io … TLS handshake timeout`.

### Previous [commit](https://github.com/metasfresh/metasfresh/commit/0a7da1e7c5d) — [this CI run](https://github.com/metasfresh/metasfresh/actions/runs/33628777770), build `5.175-soft-panda-hotfix-MobileJobStartHarnessFakePage.43004`

| Attempt | Check | Failing test | Classification | Evidence it is not ours |
|---|---|---|---|---|
| [1](https://github.com/metasfresh/metasfresh/actions/runs/33628777770/job/100249213198) | `mobile test` — 1 failed / 251 passed (22.9m) | `humanager/huManager.spec.js:155` `Bulk actions - Move` | Known flake — internal flaky-case 38 (HU-manager app-list settle seam) | Base-branch reproduction, below |
| [1](https://github.com/metasfresh/metasfresh/actions/runs/33628777770/job/100249213458) | `test (cucumber) (profile3)` — 1 failed / 164 | `syncEANAndGTIN.feature:230` "TC-12 Sysconfig missing - behaves as sync ON" | Not ours — new intermittent; internal flaky-case 91 (missing-sysconfig default-ON leg — writing `GTIN` must auto-fill `UPC`; scenario at feature `:221`, failing step `:230`), filed separately from flaky-case 56 because that one drives the inverse `EAN13`→clear leg with the sysconfig explicitly ON | Reachability, below |
| [2](https://github.com/metasfresh/metasfresh/actions/runs/33628777770/job/100262717749) | `mobile test` | none — died pulling its image | **Infrastructure** — flaky-case 90 | `Get "https://ghcr.io/v2/": net/http: TLS handshake timeout` |
| [2](https://github.com/metasfresh/metasfresh/actions/runs/33628777770/job/100262719548) | `test (cucumber) (profile3)` | none — same | **Infrastructure** — flaky-case 90 | same `ghcr.io … TLS handshake timeout` |

Both attempt-1 failures are confirmed by [`failures.json` for build `.43004`](https://test-reports.metasfresh.com/branches/soft-panda-hotfix-mobilejobstartharnessfakepage/builds/5.175-soft-panda-hotfix-MobileJobStartHarnessFakePage.43004/failures.json) — cucumber 1/1012, mobile-webui 1/252.

**`humanager/huManager.spec.js:155`** — `TimeoutError: locator.waitFor: Timeout 40000ms exceeded` waiting for `#ApplicationsListScreen` to be visible (`ApplicationsListScreen.js:15` ← `HUBulkActionsScreen.js:39` ← `HUManagerScreen.js:93`). A long-standing HU-manager app-list settle seam.
- **Base-branch counterfactual (decisive):** the same seam fails on `soft_panda_hotfix` the same day with **no PR content** — build `5.175-soft-panda-hotfix.42983` ([this base-branch run](https://github.com/metasfresh/metasfresh/actions/runs/33609632115), [`mobile test`](https://github.com/metasfresh/metasfresh/actions/runs/33609632115/job/100187192442)) has **this exact spec plus its sibling** red, 2 failed / 250 passed; build `5.175-soft-panda-hotfix.42991` ([a later base-branch run](https://github.com/metasfresh/metasfresh/actions/runs/33612986819), [`mobile test`](https://github.com/metasfresh/metasfresh/actions/runs/33612986819/job/100198297249)) has the sibling red, 1 failed / 251 passed.
- **Reachability: none.** `humanager/huManager.spec.js` imports `Backend`, `LoginScreen`, `ApplicationsListScreen`, `HUManagerScreen`, `ClearanceDialog` — not one file in this diff, and no `startJob` / `jobStartRecovery` reference anywhere in it. On the production side `#ApplicationsListScreen` is `containers/applicationsListScreen/ApplicationsListScreen.jsx`, whose only store read is `getAvailableApplicationsArray` from `reducers/applications` — never `api/launchers.js`.

**`syncEANAndGTIN.feature:230` (TC-12)** — `[UPC] expected: "4012345678901" but was: null`, at `M_Product_StepDef.m_product_is_verified` (`:446`) via `DataTableRows.forEach`.
- **Reachability: none.** This PR's 4 files are three E2E Playwright files under `e2e/mobile-webui/tests/` plus a 3-line local-variable rename in `misc/services/mobile-webui/mobile-webui-frontend/src/api/launchers.js`. The cucumber suite exercises backend Java and touches none of it.
- **Provenance:** the scenario (`@Id:S0612_120`) has been in the tree unchanged since [this commit](https://github.com/metasfresh/metasfresh/commit/d3890e3c443) (2026-03-11) — six months, not something this work introduced. A sibling scenario in the same feature file has a tracked same-commit pass/fail flip on this branch line, with the inverse assertion direction (`GTIN` not cleared) — flaky-case 56.
- **Caveat, stated honestly:** no same-commit pass was observed for TC-12 itself here, because attempt 2's `profile3` died on the image pull before running any test. Reachability alone excludes this PR; the intermittency classification rests on the sibling scenario's history, not on a green re-run of this commit.

**Comment by teosarca** [comment]
## Integration decision — merging with one accepted red

**Head being merged: `eb8ee8a01274627a8882d2abe32de5d0b308d7fb`.** Re-stating the disposition at this exact sha, since the head moved after the earlier CI audit on this PR.

**The only red: `mobile test`** (plus `Merge Gate`, which is just its aggregate — no independent failure).

It is **flaky-registry case 38**: `huManager.spec.js:155` *"Bulk actions - Move"*, a 40 s `waitFor` on `#ApplicationsListScreen` at `ApplicationsListScreen.js:15` ← `HUBulkActionsScreen.js:39` ← `HUManagerScreen.js:93`. 60 recorded occurrences, tier 9.

Why it is not attributable to this diff, and why it cannot be cleared here:

1. **It is red on the `soft_panda_hotfix` base branch itself** (build `.42983`), independently of this PR.
2. **It is a different seam from the one this branch fixes.** This work addresses case 01 (`job-start-seam`, the mobile GRAI specs). Case 38 is the huManager bulk-actions seam; the registry records the two being separated by a re-partitioned run on one sha, where case 01 passed and case 38 still failed.
3. **The fix for case 38 is someone else's, and is still open:** https://github.com/metasfresh/metasfresh/pull/25613.
4. **Rerunning is the wrong instrument.** Case 38's per-sha rerun ledger: of the 6 shas that have had 2+ `mobile test` executions, the job reached green on only 2 — the others never cleared within 4, 5, 4 and 2+ attempts.

**Decision:** the maintainer has accepted this check. The acceptance is recorded sha-bound in `.git/claude-ci-approval`, so it applies only while `eb8ee8a0127` is the head — any new push voids it.

Merged with `--squash`: this is a regular feature PR (head `soft_panda_hotfix_MobileJobStartHarnessFakePage`), not an integration branch.
